### ISSUE TITLE
为什么不能自动生成dll 我还以为是自动

### ISSUE THREAD

**Issue by Astra-520** [L0serQianXia/LetsUseNativeObfuscator#2]

**Comment by L0serQianXia** [comment]
您好，这边是支持自动生成DLL的。没有生成的话可能是某个cpp文件编译失败，或目录过长且文件过多，导致超出了命令行最多字符限制而无法执行编译命令。您如果确认将执行的命令行参数不会超出限制，请尝试旧版本（新版本recode大部分代码 可能有兼容问题）

**Comment by Astra-520** [comment]
是我必须把jar也放进cpp文件夹才会吗

**Comment by Astra-520** [comment]
[INFO]Packing the JAR with DLL
Jar File or DLL File not Found!!!
Jar File or DLL File not Found!!!
[INFO]Finished.

**Comment by L0serQianXia** [comment]
> [INFO]Packing the JAR with DLL Jar File or DLL File not Found!!! Jar File or DLL File not Found!!! [INFO]Finished.

这个是将DLL文件打包到jar文件中的步骤，这里检测的jar文件是您使用native混淆器后生成的默认位置

**Comment by L0serQianXia** [comment]
> 是我必须把jar也放进cpp文件夹才会吗

jar文件是否存在并不影响dll文件的生成

**Comment by Astra-520** [comment]
根据他的log来看 我的每个cpp都编译成功了啊

**Comment by Astra-520** [comment]
但是没有dll

**Comment by Astra-520** [comment]
[INFO]Packing the JAR with DLL
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
        at java.lang.reflect.Method.invoke(Unknown Source)
        at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61)
Caused by: java.lang.NullPointerException
        at java.io.File.<init>(Unknown Source)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.packJar(GoodNativeObfuscator.java:210)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.packJar(GoodNativeObfuscator.java:102)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.main(GoodNativeObfuscator.java:64)
        ... 5 more

**Comment by L0serQianXia** [comment]
> [INFO]Packing the JAR with DLL Exception in thread "main" java.lang.reflect.InvocationTargetException at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) at java.lang.reflect.Method.invoke(Unknown Source) at org.eclipse.jdt.internal.jarinjarloader.JarRsrcLoader.main(JarRsrcLoader.java:61) Caused by: java.lang.NullPointerException at java.io.File.(Unknown Source) at me.qianxia.goodnativeobf.GoodNativeObfuscator.packJar(GoodNativeObfuscator.java:210) at me.qianxia.goodnativeobf.GoodNativeObfuscator.packJar(GoodNativeObfuscator.java:102) at me.qianxia.goodnativeobf.GoodNativeObfuscator.main(GoodNativeObfuscator.java:64) ... 5 more

您好，这个应该是找不到jar文件引起的，这里会默认在运行目录的上一级寻找后缀名为jar的文件

**Comment by Astra-520** [comment]
你好 上一级有jar

**Comment by Astra-520** [comment]
可以写一个自动native混 自动打包dll 自动将dll塞入jar的工具吗

**Comment by Astra-520** [comment]
java.io.IOException: Cannot run program "g++": CreateProcess error=206, 文件名或扩展名太长。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.compileCpp(GoodNativeObfuscator.java:131)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.main(GoodNativeObfuscator.java:50)
Caused by: java.io.IOException: CreateProcess error=206, 文件名或扩展名太长。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 6 more
java.io.IOException: Cannot run program "g++": CreateProcess error=206, 文件名或扩展名太长。
        at java.lang.ProcessBuilder.start(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at java.lang.Runtime.exec(Unknown Source)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.compileCpp(GoodNativeObfuscator.java:137)
        at me.qianxia.goodnativeobf.GoodNativeObfuscator.main(GoodNativeObfuscator.java:50)
Caused by: java.io.IOException: CreateProcess error=206, 文件名或扩展名太长。
        at java.lang.ProcessImpl.create(Native Method)
        at java.lang.ProcessImpl.<init>(Unknown Source)
        at java.lang.ProcessImpl.start(Unknown Source)
        ... 6 more
packing the JAR with DLL
32bit DLL Not Found!!!
Finished.

**Comment by L0serQianXia** [comment]
目前解决了无法编译dll的问题，因为编译参数写错了。但是对于你的异常信息，暂时没有好的解决办法直到我改变编译方式

**Comment by L0serQianXia** [comment]
> java.io.IOException: Cannot run program "g++": CreateProcess error=206, 文件名或扩展名太长。 at java.lang.ProcessBuilder.start(Unknown Source) at java.lang.Runtime.exec(Unknown Source) at java.lang.Runtime.exec(Unknown Source) at java.lang.Runtime.exec(Unknown Source) at me.qianxia.goodnativeobf.GoodNativeObfuscator.compileCpp(GoodNativeObfuscator.java:131) at me.qianxia.goodnativeobf.GoodNativeObfuscator.main(GoodNativeObfuscator.java:50) Caused by: java.io.IOException: CreateProcess error=206, 文件名或扩展名太长。 at java.lang.ProcessImpl.create(Native Method) at java.lang.ProcessImpl.(Unknown Source) at java.lang.ProcessImpl.start(Unknown Source) ... 6 more java.io.IOException: Cannot run program "g++": CreateProcess error=206, 文件名或扩展名太长。 at java.lang.ProcessBuilder.start(Unknown Source) at java.lang.Runtime.exec(Unknown Source) at java.lang.Runtime.exec(Unknown Source) at java.lang.Runtime.exec(Unknown Source) at me.qianxia.goodnativeobf.GoodNativeObfuscator.compileCpp(GoodNativeObfuscator.java:137) at me.qianxia.goodnativeobf.GoodNativeObfuscator.main(GoodNativeObfuscator.java:50) Caused by: java.io.IOException: CreateProcess error=206, 文件名或扩展名太长。 at java.lang.ProcessImpl.create(Native Method) at java.lang.ProcessImpl.(Unknown Source) at java.lang.ProcessImpl.start(Unknown Source) ... 6 more packing the JAR with DLL 32bit DLL Not Found!!! Finished.

尽我最大能力修复了一下这个问题，使用了相对路径，避免了参数过长
